spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
  
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

#zuul服务转发默认规则，可以不写，除非有特殊需求
#zuul:
#  routes:
#   item-service: /item-service/**
#    user-service: /user-service/**
#   order-service: /order-service/**

#zuul 默认不推荐使用重试，需要配置才能使用
zuul:
  retryable: true
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1